[package]
name = "ablaze"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
rand = "0.9.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1.3"
